
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: vote
  template: 
    metadata: 
      name: nginx
      lebels:
        app: vote
    spec: 
      containers:
      - name: nginx
        image: nginx
